### PR TITLE
Clean & update build.gradle

### PR DESCRIPTION
**Pull request by rozPierog**
I've cleaned `build.gradle` form junk that is not needed in plugin, and also updated its SdkVersions, buildToolsVersion and appcompat library to modern standards

### CODE REVIEW

**Comment by roadev** [comment]
+1 !

**Comment by rtkhanas** [comment]
@greedbell can you merge and publish this to NPM, please? 🙏

**Comment by greedbell** [comment]
@rtkhanas it's merged and published

**Comment by rtkhanas** [comment]
@greedbell thank you a lot! 😃

**Pull request merged**
